### ISSUE TITLE
Extend Destructive Changes: Warn if default is removed from an underlying column

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#182]
By looking at the Magento database we learned that there are database schemas that use a default value on columns with a foreign key. If a user would start to use lift on such a database the default values would get silently removed. Hence we want to incorporate this into our destructive changes checking:
* The `migration-engine` must return a destructive warning if a column default gets removed.

**Comment by tomhoule** [comment]
Status update: started looking into this, but it depended on migrating defaults in general, and that is still pending (PR open and waiting for review), so it's blocked for now.

**Comment by tomhoule** [comment]
https://github.com/prisma/prisma-engine/pull/235  (mentioned in previous comment)

**Comment by tomhoule** [comment]
PR: https://github.com/prisma/prisma-engine/pull/277

Currently blocked on other PRs, will keep this issue up to date

**Comment by tomhoule** [comment]
Update: this was blocked for a while because we wondered about supporting defaults on relation fields in introspection and the query engine.

Since we won't support this, the destructive change check is needed. The PR mentioned above need a bit more work to give more context to the SqlDestructiveChangeChecker. It will happen as soon as I am done with my higher priority tasks.
